import type { Metadata } from "next";
import { inter } from "./fonts";
import { Provider } from "../components/ui/provider";
import "./globals.css";
import Header from "../components/Header/Header";
import ReactQueryProvider from "../providers/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased`}
        suppressHydrationWarning
      >
        <Provider>
          <ReactQueryProvider>
            <Header />
            {children}
          </ReactQueryProvider>
        </Provider>
      </body>
    </html>
  );
}
