import type { Metadata } from "next";
import { inter } from "./fonts";
import { Provider } from "../components/ui/provider";
import "./globals.css";
import Header from "../components/Header/Header";
import ReactQueryProvider from "../providers/ReactQueryProvider";
import Footer from "../components/Footer/Footer";
import { ThemeProvider } from "../context/ThemeContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider>
          <Provider>
            <ReactQueryProvider>
              <Header />
              {children}
              <Footer />
            </ReactQueryProvider>
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
